import { Project } from '@/types/projectType';

export const projects: Project[] = [
  {
    id: 'riverside-district',
    title: 'Riverside District',
    description: 'A premier mixed-use development featuring luxury residential units and ground-floor commercial spaces along the waterfront.',
    heroImage: '/properties/riverside-hero.jpg',
    fullDescription: 'Riverside District represents the pinnacle of urban living, combining sophisticated residential units with vibrant commercial spaces. This waterfront development features thoughtful architecture, premium finishes, and amenities designed for the modern professional. The project includes 120 residential units ranging from one to three bedrooms, alongside 15,000 square feet of retail space, creating a dynamic live-work-play environment.',
    technologies: ['Luxury Finishes', 'Smart Home Technology', 'Sustainable Design', 'Mixed-Use', 'Waterfront Location'],
    features: [
      '120 residential units with river views',
      'Ground-floor retail and dining establishments',
      'Rooftop amenity deck with grilling stations',
      'State-of-the-art fitness center and yoga studio',
      'Secured parking with EV charging stations',
    ],
    gallery: [
      '/properties/riverside-exterior.jpg',
      '/properties/riverside-lobby.jpg',
      '/properties/riverside-unit.jpg',
      '/properties/riverside-amenities.jpg',
      '/properties/riverside-rooftop.jpg',
      '/properties/riverside-retail.jpg',
    ],
    links: {
      demo: '#',
      github: '#',
    },
  },
  {
    id: 'heritage-commons',
    title: 'Heritage Commons',
    description: 'Historic building adaptive reuse project transforming a landmark structure into upscale commercial office space.',
    heroImage: '/properties/heritage-hero.jpg',
    fullDescription: 'Heritage Commons breathes new life into a beloved historic landmark while preserving its architectural integrity. This adaptive reuse project converts a century-old building into 50,000 square feet of Class A office space, featuring exposed brick, original hardwood floors, and modern amenities. The development honors the past while providing contemporary functionality for today\'s businesses, including tech startups and creative agencies.',
    technologies: ['Historic Preservation', 'Adaptive Reuse', 'Class A Office', 'LEED Certified', 'Downtown Location'],
    features: [
      'Original architectural elements preserved and restored',
      '50,000 sq ft of flexible office space',
      'Modern HVAC and building systems',
      'High-speed fiber internet infrastructure',
      'On-site parking and bike storage',
    ],
    gallery: [
      '/properties/heritage-facade.jpg',
      '/properties/heritage-brick.jpg',
      '/properties/heritage-office.jpg',
      '/properties/heritage-lobby.jpg',
      '/properties/heritage-conference.jpg',
      '/properties/heritage-courtyard.jpg',
    ],
    links: {
      demo: '#',
      github: '#',
    },
  },
  {
    id: 'oakmont-estates',
    title: 'Oakmont Estates',
    description: 'Exclusive single-family residential community featuring custom-designed homes on generous lots with premium amenities.',
    heroImage: '/properties/oakmont-hero.jpg',
    fullDescription: 'Oakmont Estates offers an unparalleled living experience in a thoughtfully planned residential community. This exclusive development features 45 custom single-family homes on spacious lots, each designed with meticulous attention to detail and quality craftsmanship. Residents enjoy access to private amenities including a community clubhouse, resort-style pool, and landscaped walking trails, all within a secure, gated environment.',
    technologies: ['Single-Family Homes', 'Custom Design', 'Gated Community', 'Premium Lots', 'Suburban Location'],
    features: [
      '45 custom-designed homes from 3,200 to 5,500 sq ft',
      'Oversized lots ranging from 0.5 to 1.2 acres',
      'Private community clubhouse and pool complex',
      'Professionally landscaped common areas',
      'Highly-rated school district access',
    ],
    gallery: [
      '/properties/oakmont-exterior.jpg',
      '/properties/oakmont-kitchen.jpg',
      '/properties/oakmont-master.jpg',
      '/properties/oakmont-pool.jpg',
      '/properties/oakmont-clubhouse.jpg',
      '/properties/oakmont-landscape.jpg',
    ],
    links: {
      demo: '#',
      github: '#',
    },
  },
];
